backend:
  name: github
  repo: Tech-C-Venture/HP
  branch: main
  base_url: https://f-tcv.com
  auth_endpoint: api/auth

# ローカル開発用の設定（本番環境ではコメントアウト）
# local_backend: true

# メディアファイルの設定
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Cloudflare R2との連携設定
media_library:
  name: uploadcare
  config:
    publicKey: "your_uploadcare_public_key"
    multiple: false
    tabs: "file camera url"
    effects: "crop,rotate,enhance"

# サイト設定
site_url: https://techc-venture.com
display_url: https://techc-venture.com
logo_url: /images/logo/logo.png

# 日本語設定
locale: 'ja'

# エディタの設定
editor:
  preview: true

# コレクション定義
collections:
  # ブログ記事
  - name: "blog"
    label: "ブログ記事"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "説明", name: "description", widget: "text", required: true }
      - { label: "公開日", name: "date", widget: "datetime", required: true }
      - {
          label: "カテゴリ",
          name: "category",
          widget: "select",
          options: ["お知らせ", "技術", "開発", "イベント", "メンバー"],
          required: true
        }
      - { label: "公開状態", name: "published", widget: "boolean", default: true }
      - {
          label: "アイキャッチ画像",
          name: "image",
          widget: "image",
          required: false,
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - { label: "著者", name: "author", widget: "string", required: false }
      - { label: "タグ", name: "tags", widget: "list", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: true }

  # 協力企業
  - name: "partners"
    label: "協力企業"
    folder: "content/partners"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "企業名", name: "name", widget: "string", required: true }
      - { label: "URL", name: "url", widget: "string", required: true }
      - {
          label: "ロゴ",
          name: "logo",
          widget: "image",
          required: true,
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - { label: "説明", name: "description", widget: "text", required: true }
      - {
          label: "パートナータイプ",
          name: "type",
          widget: "select",
          options: ["ゴールドパートナー", "シルバーパートナー", "サポートパートナー"],
          required: true
        }
      - { label: "支援内容", name: "support", widget: "string", required: true }
      - { label: "表示順", name: "order", widget: "number", default: 0 }
      - { label: "公開状態", name: "published", widget: "boolean", default: true }

  # メンター
  - name: "mentors"
    label: "メンター"
    folder: "content/mentors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "名前", name: "name", widget: "string", required: true }
      - { label: "役職", name: "role", widget: "string", required: true }
      - {
          label: "プロフィール画像",
          name: "avatar",
          widget: "image",
          required: true,
          media_library: {
            config: {
              multiple: false
            }
          }
        }
      - { label: "自己紹介", name: "description", widget: "text", required: true }
      - { label: "スキル", name: "skills", widget: "list", required: true }
      - { label: "GitHub", name: "github", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
      - { label: "表示順", name: "order", widget: "number", default: 0 }
      - { label: "公開状態", name: "published", widget: "boolean", default: true }

  # サイト設定
  - name: "settings"
    label: "サイト設定"
    files:
      - label: "サイト情報"
        name: "site"
        file: "content/settings/site.yml"
        fields:
          - { label: "サイト名", name: "title", widget: "string" }
          - { label: "説明", name: "description", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "メールアドレス", name: "email", widget: "string" }
          - {
              label: "ロゴ",
              name: "logo",
              widget: "image",
              media_library: {
                config: {
                  multiple: false
                }
              }
            }

      - label: "ナビゲーション"
        name: "navigation"
        file: "content/settings/navigation.yml"
        fields:
          - label: "メニュー"
            name: "menu"
            widget: "list"
            fields:
              - { label: "ラベル", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "外部リンク", name: "external", widget: "boolean", default: false }

      - label: "ソーシャルメディア"
        name: "social"
        file: "content/settings/social.yml"
        fields:
          - label: "ソーシャルリンク"
            name: "links"
            widget: "list"
            fields:
              - { label: "プラットフォーム", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "アイコン", name: "icon", widget: "string" }

# ワークフロー設定
publish_mode: editorial_workflow

# プレビュー設定
show_preview_links: true

# 検索機能
search: true

# 認証設定（GitHubベース）
# 本番環境ではGitHub Appの設定が必要