# Cloudflare Pages configuration
name = "techc-venture"
compatibility_date = "2024-09-19"

[env.production]
# 本番環境の設定

[env.preview]
# プレビュー環境の設定

# Functions設定（Cloudflare Pages Functions）
[build]
command = "npm run build"
destination = ".output/public"

# 環境変数（実際の値はCloudflare Pagesの管理画面で設定）
[vars]
NUXT_PUBLIC_SITE_URL = "https://techc-venture.com"

# R2バインディング（CloudflareWorkerでR2を使用する場合）
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "techc-venture-images"